[server]
host = "0.0.0.0"
port = 8080

[log]
dir = "logs"
max_size = 5242880 # 5MB
max_count = 3

[tvname]
file = "config_tv_name.toml"

[rapidapi]
key = ""
host = ""

[mteam]
seed_dir = ""
source_id = 0
group_id = 0
api_url = ""
api_key = ""
img_api_url = ""
img_api_key = ""

[tgbot]
token = ""
chat_id = ""

[ptgen]
url = ""
